# Form implementation generated from reading ui file 'D:\CODE\Baitap\Bai85\ui\Login\Login_MainWindow85.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(710, 449)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 50, 331, 61))
        self.label.setStyleSheet("\n"
"font: 18pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(131, 253, 255);")
        self.label.setObjectName("label")
        self.UserName = QtWidgets.QLabel(parent=self.centralwidget)
        self.UserName.setGeometry(QtCore.QRect(130, 180, 91, 21))
        self.UserName.setObjectName("UserName")
        self.Password = QtWidgets.QLabel(parent=self.centralwidget)
        self.Password.setGeometry(QtCore.QRect(130, 250, 91, 21))
        self.Password.setObjectName("Password")
        self.lineEdit_Username = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_Username.setGeometry(QtCore.QRect(250, 171, 261, 51))
        self.lineEdit_Username.setObjectName("lineEdit_Username")
        self.lineEdit_Password = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_Password.setGeometry(QtCore.QRect(250, 230, 261, 51))
        self.lineEdit_Password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.lineEdit_Password.setObjectName("lineEdit_Password")
        self.checkBox = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(420, 300, 121, 20))
        self.checkBox.setObjectName("checkBox")
        self.pushButton_save = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_save.setGeometry(QtCore.QRect(390, 350, 93, 28))
        self.pushButton_save.setObjectName("pushButton_save")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(510, 350, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 710, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#ff0000;\">Login Screen</span></p></body></html>"))
        self.UserName.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">UserName:</span></p></body></html>"))
        self.Password.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">Password:</span></p></body></html>"))
        self.lineEdit_Username.setText(_translate("MainWindow", "teo"))
        self.lineEdit_Password.setText(_translate("MainWindow", "123"))
        self.checkBox.setText(_translate("MainWindow", "Save information"))
        self.pushButton_save.setText(_translate("MainWindow", "Login"))
        self.pushButton_2.setText(_translate("MainWindow", "Exit"))
